releaseType: java-yoshi
bumpMinorPreMajor: true
handleGHRelease: true
branches:
  - branch: 1.21.x
  - branch: protobuf-4.x-rc
    manifest: true
  - releaseType: java-backport
    bumpMinorPreMajor: true
    handleGHRelease: true
    extraFiles:
      - README.md
    branch: 2.35.x
extraFiles:
  - README.md
