releaseType: java-yoshi
bumpMinorPreMajor: true
handleGHRelease: true
branches:
- branch: 1.21.x
  releaseType: java-yoshi
  bumpMinorPreMajor: true
  handleGHRelease: true
- branch: protobuf-4.x-rc
  releaseType: java-yoshi
  bumpMinorPreMajor: true
  handleGHRelease: true
  manifest: true
extraFiles: ["README.md"]
