custom_content: |
   ### Creating a JDBC Connection
   
   The following example shows how to create a JDBC connection to Cloud Spanner and execute a simple query.
   
   ```java
   String projectId = "my-project";
   String instanceId = "my-instance";
   String databaseId = "my-database";
   
   try (Connection connection =
       DriverManager.getConnection(
           String.format(
               "jdbc:cloudspanner:/projects/%s/instances/%s/databases/%s",
               projectId, instanceId, databaseId))) {
     try (Statement statement = connection.createStatement()) {
       try (ResultSet rs = statement.executeQuery("SELECT CURRENT_TIMESTAMP()")) {
         while (rs.next()) {
           System.out.printf(
               "Connected to Cloud Spanner at [%s]%n", rs.getTimestamp(1).toString());
         }
       }
     }
   }
   ```
   
   ### Jar with Dependencies
   A single jar with all dependencies can be downloaded from https://repo1.maven.org/maven2/com/google/cloud/google-cloud-spanner-jdbc/latest
   or be built with the command `mvn package` (select the jar that is named `google-cloud-spanner-jdbc-<version>-single-jar-with-dependencies.jar`).
   
   ### Creating a Shaded Jar
   
   A jar with all dependencies included is automatically generated when you execute `mvn package`.
   The dependencies in this jar are not shaded. To create a jar with shaded dependencies you must
   activate the `shade` profile like this:
   
    ```
    mvn package -Pshade
    ```
   