on:
  pull_request:
name: samples
jobs:
  checkstyle:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: stCarolas/setup-maven@v4
        with:
          maven-version: 3.8.1
      - uses: actions/setup-java@v1
        with:
          java-version: 8
      - name: Run checkstyle
        run: mvn -P lint --quiet --batch-mode checkstyle:check
        working-directory: samples/snippets
